### ISSUE TITLE
INCOMPATIBILITY WITH NBT: fail to get hash code, very early pipeline error

### ISSUE THREAD

**Issue by milecombo** [meegpipe/meegpipe#23]
hi, 
I am trying to use meegpipe as a wrapper to extract features at the subject level, hence I am making links to cleaned data, and not copying the data.
meegpipe version is the latest, the one with  the download link posted in the previous issue
>
myFirstLevelFeature  = {@(x, ev, dataSel) mpfeat_pset2nbt_doAll(x)}; %dallbm
%%% 2nd level is a dummy pass
mySecondLevelFeature = {@(x, ev, dataSel) x}; %x(1)/x(2),  @(x, selectorArray) mean(x)};
myConfig = meegpipe.node.generic_features.config(...
    'TargetSelector', {myDataSel}, ... %, mySel2, mySel3
    'FirstLevel',     myFirstLevelFeature, ...
    'SecondLevel',    mySecondLevelFeature, ...
    'FeatureNames',   {'pset2nbt_doAll'} );
myNode = generic_features.new(myConfig);

However, when it comes to run the pipe, I get a long java error, after the very first second,
that is, before submitting the jobs to the que

>
Error using mjava.hash/get_hash_code
Method 'get_hash_code' is not defined for class 'mjava.hash' or is removed from MATLAB's search path.
Error in goo.abstract_setget/get_hash_code (line 18)
        info.(fNames{i}) = get_hash_code(obj.(fNames{i}));
Error in goo.cell2hashcode (line 9)
        cArray{i} = get_hash_code(cArray{i});
Error in goo.abstract_setget/get_hash_code (line 20)
        info.(fNames{i}) = cell2hashcode(obj.(fNames{i}))

**Comment by milecombo** [comment]
Most likely solved, 
when building the pipeline I now set 'save' to true, and jobs are properly submitted

**Comment by milecombo** [comment]
Still having troubles after setting the pipeline options 'save' to true...

**Comment by milecombo** [comment]
I again Replicated the same problem in different cases:
- running a dummy -import only- pipeline
- running the same pipe on different files

**Comment by milecombo** [comment]
SOLVED ( most likely).
removing nbt from the path solved it.
 It seems that having nbt on your path is creating this get-hash-code iisue.

**Comment by simon-shlomo** [comment]
if I just run get_hash_code(mjava.hash) it works (with NBT and meegpipe in the path).. 
then I ran meegpipe.initialize
and then get_hash_code(mjava.hash) and I get the error
Error: File: hashable.m Line: 19 Column: 19
Arguments to IMPORT must either end with ".*" or else specify a fully qualified class name: "datahash.DataHash" fails this test.

Error in mjava.hash (line 103)
        function obj = hash(varargin)


so something is wrong with the path or the 'datahash' package..
