### ISSUE TITLE
MATLAB floating point exception

### ISSUE THREAD

**Issue by germangh** [meegpipe/meegpipe#24]
This is a platform specific issue. To reproduce run:

````
tutorial_emg.tests.test_tutorial_emg
````

on somerenserver / MATLAB R2014a. This doesn't produce any error on my Mac OS X / MATLAB R2014a.

**Comment by germangh** [comment]
Absolutely no idea how to fix this. It seems to be an internal MATLAB issue. Running:

````
tutorial_emg.tests.test_tutorial_emg
````

will trigger the error on line 23 of `pset.pset.cov` when calling MATLAB's built-in `sum()` on a double precission matrix. The error does not happen everytime that that line of `pset.pset.cov` is run, but it does happen everytime that `tutorial_emg.tests.test_tutorial_emg` is run. It could also be related with some of the OS libraries at somerenserver on which MATLAB depends. So this will not be fixed.

**Comment by yishuwei** [comment]
On somerenserver / Matlab 2014a, I encountered this segmentation error almost everytime running a BSS node. On somnodes 1,2,4, this does not occur.
